name: kalyn
version: 0
author: "Radian LLC"
maintainer: "contact+kalyn@radian.codes"

dependencies:
  - base
  - bytestring
  - containers
  - deepseq
  - directory
  - filepath
  - mtl
  - pretty-simple
  - text
  - unix
  - utf8-string

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  kalyn:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
    dependencies:
      - kalyn
