name: kalyn
version: 0
author: "Radon Rosborough"
maintainer: "radon.neon@gmail.com"

dependencies:
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - MissingH
  - mtl
  - pretty-simple
  - text
  - unix
  - utf8-string

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  kalyn:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
    dependencies:
      - kalyn
